'''
fobj=open("a.txt",'r+')
print(fobj.read())
print(fobj.read(8))
fobj.close()
------------------------------
fobj=open("a.txt",'w')
fobj.write("good morning")
fobj.close()
---------------------------
fobj=open("a.txt",'r')
print(fobj.readline())
print(fobj.readline(4))
print(fobj.readlines())
print(fobj.read(8))
fobj.close()
---------------------------
fobj=open("a.txt",'r')
print(fobj.read(29))
print(fobj.readline(29))
print(fobj.readlines(29))
fobj.close()
-------------
fobj=open("a.txt",'r')
print(fobj.read(26))
print(fobj.tell())
print(fobj.readline(26))
print(fobj.tell())
print(fobj.readlines(26))
print(fobj.tell())
fobj.close()
----------------------------
fobj=open("b.txt",'r')
print(fobj.read(26))
print(fobj.tell())
print(fobj.seek(26))
print(fobj.read(10))
fobj.close()
-----------------------
fobj=open("b.txt",'w') #here new file is created in new file, but if read then FileNotFound is thrown
fobj.write("good morning")
fobj.close()
--------------------------
fobj=open("b.txt",'r')
print(fobj.read())
fobj.seek(0)
print(fobj.read(16))
print(fobj.tell())
fobj.close()
----------------------------
'''
fobj=open("b.txt",'r')
print(fobj.readline())
print(fobj.readline())
fobj.close()
